version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    # Variáveis de ambiente para conexão com o DB
    environment:
      API_PORT: 8080
      DB_HOST: database 
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: financas_db
      DB_PORT: 5432
    depends_on:
      - database

  frontend:
    # A construção está OK, já foi verificada.
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financas_db
    # Removendo o mapeamento de porta externa se não for estritamente necessário para dev local
    # ports:
    #   - "5432:5432" 
    
    # ATENÇÃO: A sintaxe de volumes estava incompleta ou corrompida. 
    # Usamos o formato 'VOLUME_EXTERNO:CAMINHO_INTERNO'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
# Volume definition MUST be at the end
volumes:
  postgres_data:

